version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5430:5432"
    networks:
      - chatapp-network

  webapp:
    build:
      context: .
    image: webapp_image
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge
